# Generated by Django 3.2.5 on 2021-08-03 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('lat', models.DecimalField(decimal_places=6, help_text='Latitud en notación decimal.', max_digits=10, verbose_name='Latitud(Decimal)')),
                ('lng', models.DecimalField(decimal_places=6, help_text='Latitud en notación decimal.', max_digits=10, verbose_name='Longitud(Decimal')),
            ],
            options={
                'verbose_name_plural': 'Comunidades',
                'ordering': ['municipio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cedula', models.CharField(help_text='Cédula de identidad sin guiones', max_length=14, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(blank=True, help_text='8888-8888', max_length=9, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['institucion', 'apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('elemento', models.CharField(max_length=45)),
                ('codigo_eq', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de equivalencia')),
            ],
            options={
                'verbose_name': 'Detalle de Tabla',
                'verbose_name_plural': 'Detalles de Tabla',
                'ordering': ['tabla', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('siglas', models.CharField(max_length=25)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('web', models.URLField(blank=True, max_length=150, null=True)),
                ('sector', models.ForeignKey(help_text='Sector que atiende la institución.', limit_choices_to=models.Q(('tabla__tabla', 'sectores')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones_sectores', related_query_name='institucion_sector', to='sispro.detalletabla')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['sector', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_corto', models.CharField(max_length=10)),
                ('region', models.CharField(choices=[('raccs', 'Región Autónoma de la Costa Caribe Sur'), ('raccn', 'Región Autónoma de la Costa Caribe Norte')], default='raccs', max_length=5)),
                ('area', models.DecimalField(decimal_places=2, help_text='Extensión en Km^2', max_digits=8, null=True)),
                ('poblacion', models.IntegerField(null=True, verbose_name='Población aprox.')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200)),
                ('acronimo', models.CharField(max_length=45, verbose_name='Acrónimo')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('finalizado', models.BooleanField(default=False)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sispro.institucion')),
                ('sector', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'sectores')), on_delete=django.db.models.deletion.RESTRICT, to='sispro.detalletabla')),
            ],
            options={
                'ordering': ['finalizado', 'sector', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Protagonista',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cedula', models.CharField(help_text='Cédula de identidad sin guiones', max_length=14, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(help_text='8888-8888', max_length=9, verbose_name='Teléfono')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sispro.comunidad')),
                ('etnia', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'etnias')), on_delete=django.db.models.deletion.RESTRICT, to='sispro.detalletabla')),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tabla', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200)),
                ('acronimo', models.CharField(max_length=45, verbose_name='Acrónimo')),
                ('finalizado', models.BooleanField(default=False)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sispro.contacto')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sispro.institucion')),
                ('programa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sispro.programa')),
                ('sector', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'sectores')), on_delete=django.db.models.deletion.RESTRICT, to='sispro.detalletabla')),
            ],
            options={
                'ordering': ['finalizado', 'sector', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProtagonistaBono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_recibido', models.DateField(help_text='Fecha en que recibió el Bono/Plan de inversión.')),
                ('coord_x', models.FloatField(verbose_name='Coordenada UTM-X')),
                ('coord_y', models.FloatField(verbose_name='Coordenada UTL-Y')),
                ('altura', models.IntegerField(null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Está activo para seguimiento.')),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sispro.bono')),
                ('comunidad', models.ForeignKey(help_text='Comunidad donde se ejecuta.', on_delete=django.db.models.deletion.PROTECT, to='sispro.comunidad')),
                ('protagonista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sispro.protagonista')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sispro.proyecto')),
                ('tecnico', models.ForeignKey(help_text='Técnico que realizó la entrega.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='sispro.contacto')),
            ],
            options={
                'verbose_name': 'Protagonista con Bono/Plan',
                'verbose_name_plural': 'Protagonistas con Bonos/Planes',
                'ordering': ['protagonista', '-fecha_recibido', 'bono'],
            },
        ),
        migrations.AddField(
            model_name='detalletabla',
            name='tabla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sispro.tabla'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='cargo',
            field=models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'cargos')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_cargos', related_query_name='contacto_cargo', to='sispro.detalletabla'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='comunidad',
            field=models.ForeignKey(help_text='Comunidad de residencia', on_delete=django.db.models.deletion.RESTRICT, to='sispro.comunidad'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='etnia',
            field=models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'etnias')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_etnias', related_query_name='contacto_etnia', to='sispro.detalletabla'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sispro.institucion'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(help_text='Requerido sólo si el usuario tendrá acceso a digitar o extraer datos.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='actividades_ec',
            field=models.ManyToManyField(help_text='Actividades económicas desarrolladas en la comunidad.', limit_choices_to=models.Q(('tabla__tabla', 'actividades_ec')), related_name='_sispro_comunidad_actividades_ec_+', to='sispro.DetalleTabla'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sispro.municipio'),
        ),
        migrations.CreateModel(
            name='CapitalizacionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo en Córdobas(C$)', max_digits=8, verbose_name='Costo unitario')),
                ('articulo', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'articulos')), on_delete=django.db.models.deletion.RESTRICT, related_name='capitalizaciones_articulos', related_query_name='capitalizacion_articulo', to='sispro.detalletabla')),
                ('protagonista_bono', models.ForeignKey(limit_choices_to=models.Q(('bono__tipo', 'plan_inversion')), on_delete=django.db.models.deletion.CASCADE, to='sispro.protagonistabono')),
                ('unidad', models.ForeignKey(help_text='Unidad de Medida', limit_choices_to=models.Q(('tabla__tabla', 'unidades')), on_delete=django.db.models.deletion.RESTRICT, related_name='capitalizaciones_unidades', related_query_name='capitalizacion_unidad', to='sispro.detalletabla')),
            ],
            options={
                'ordering': ['protagonista_bono'],
            },
        ),
        migrations.AddField(
            model_name='bono',
            name='sector',
            field=models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'sectores')), on_delete=django.db.models.deletion.RESTRICT, related_name='bonos_sectores', related_query_name='bono_sector', to='sispro.detalletabla'),
        ),
        migrations.AddField(
            model_name='bono',
            name='tipo',
            field=models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'tipos_bono')), on_delete=django.db.models.deletion.RESTRICT, related_name='bonos_tipos', related_query_name='bono_tipo', to='sispro.detalletabla'),
        ),
    ]
