# Generated by Django 3.2.5 on 2021-08-05 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sispro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protagonistabono',
            name='digitador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capitalizacionplan',
            name='protagonista_bono',
            field=models.ForeignKey(limit_choices_to=models.Q(('bono__tipo__elemento', 'plan_inversion')), on_delete=django.db.models.deletion.CASCADE, to='sispro.protagonistabono'),
        ),
    ]
