# Generated by Django 3.2.5 on 2021-08-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sispro', '0002_auto_20210805_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='protagonista',
            name='jvc',
            field=models.BooleanField(default=False, verbose_name='Miembro de JVC'),
        ),
        migrations.AddField(
            model_name='protagonista',
            name='promotor',
            field=models.BooleanField(default=False, verbose_name='Es Promotor'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='protagonista',
            name='telefono',
            field=models.CharField(blank=True, help_text='8888-8888', max_length=9, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='protagonistabono',
            name='altura',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protagonistabono',
            name='coord_y',
            field=models.FloatField(verbose_name='Coordenada UTM-Y'),
        ),
    ]
