# Generated by Django 3.2.5 on 2021-08-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sispro', '0003_auto_20210810_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sispro.programa'),
        ),
    ]
